insert into HOTEL values (default, 'Ibis', 'Sydney');
insert into HOTEL values (default, 'Mecure', 'Melbourne');
insert into HOTEL values (default, 'Ibis', 'Brisbane');
insert into HOTEL values (default, 'Ibis', 'Adelaide');
insert into HOTEL values (default, 'Ibis', 'Hobart');

insert into ROOM_TYPE values (default, 'SINGLE', 70);
insert into ROOM_TYPE values (default, 'DOUBLE', 120);
insert into ROOM_TYPE values (default, 'QUEEN', 120);
insert into ROOM_TYPE values (default, 'EXECUTIVE', 180);
insert into ROOM_TYPE values (default, 'SUITE', 300);

-- Sydney hotel
insert into ROOM values (default, 1, 101, 'available', 1);
insert into ROOM values (default, 1, 102, 'available', 1);
insert into ROOM values (default, 1, 103, 'available', 1);
insert into ROOM values (default, 1, 104, 'available', 1);
insert into ROOM values (default, 1, 105, 'available', 1);
insert into ROOM values (default, 1, 106, 'available', 1);
insert into ROOM values (default, 1, 107, 'available', 1);
insert into ROOM values (default, 1, 108, 'available', 1);
insert into ROOM values (default, 1, 109, 'available', 1);
insert into ROOM values (default, 1, 110, 'available', 1);
insert into ROOM values (default, 1, 111, 'available', 1);
insert into ROOM values (default, 1, 112, 'available', 1);
insert into ROOM values (default, 1, 113, 'available', 1);
insert into ROOM values (default, 1, 114, 'available', 1);
insert into ROOM values (default, 1, 115, 'available', 1);
insert into ROOM values (default, 2, 116, 'available', 1);
insert into ROOM values (default, 2, 117, 'available', 1);
insert into ROOM values (default, 2, 118, 'available', 1);
insert into ROOM values (default, 2, 119, 'available', 1);
insert into ROOM values (default, 2, 120, 'available', 1);
insert into ROOM values (default, 2, 121, 'available', 1);
insert into ROOM values (default, 2, 122, 'available', 1);
insert into ROOM values (default, 2, 123, 'available', 1);
insert into ROOM values (default, 2, 124, 'available', 1);
insert into ROOM values (default, 2, 125, 'available', 1);
insert into ROOM values (default, 3, 126, 'available', 1);
insert into ROOM values (default, 3, 127, 'available', 1);
insert into ROOM values (default, 3, 128, 'available', 1);
insert into ROOM values (default, 3, 129, 'available', 1);
insert into ROOM values (default, 3, 130, 'available', 1);
insert into ROOM values (default, 3, 131, 'available', 1);
insert into ROOM values (default, 3, 132, 'available', 1);
insert into ROOM values (default, 3, 133, 'available', 1);
insert into ROOM values (default, 3, 134, 'available', 1);
insert into ROOM values (default, 3, 135, 'available', 1);
insert into ROOM values (default, 4, 136, 'available', 1);
insert into ROOM values (default, 4, 137, 'available', 1);
insert into ROOM values (default, 4, 138, 'available', 1);
insert into ROOM values (default, 4, 139, 'available', 1);
insert into ROOM values (default, 4, 140, 'available', 1);
insert into ROOM values (default, 5, 141, 'available', 1);
insert into ROOM values (default, 5, 142, 'available', 1);

-- Melbourne hotel
insert into ROOM values (default, 1, 101, 'available', 2);
insert into ROOM values (default, 1, 102, 'available', 2);
insert into ROOM values (default, 1, 103, 'available', 2);
insert into ROOM values (default, 1, 104, 'available', 2);
insert into ROOM values (default, 1, 105, 'available', 2);
insert into ROOM values (default, 1, 106, 'available', 2);
insert into ROOM values (default, 1, 107, 'available', 2);
insert into ROOM values (default, 1, 108, 'available', 2);
insert into ROOM values (default, 1, 109, 'available', 2);
insert into ROOM values (default, 1, 110, 'available', 2);
insert into ROOM values (default, 1, 111, 'available', 2);
insert into ROOM values (default, 1, 112, 'available', 2);
insert into ROOM values (default, 1, 113, 'available', 2);
insert into ROOM values (default, 1, 114, 'available', 2);
insert into ROOM values (default, 1, 115, 'available', 2);
insert into ROOM values (default, 2, 116, 'available', 2);
insert into ROOM values (default, 2, 117, 'available', 2);
insert into ROOM values (default, 2, 118, 'available', 2);
insert into ROOM values (default, 2, 119, 'available', 2);
insert into ROOM values (default, 2, 120, 'available', 2);
insert into ROOM values (default, 2, 121, 'available', 2);
insert into ROOM values (default, 2, 122, 'available', 2);
insert into ROOM values (default, 2, 123, 'available', 2);
insert into ROOM values (default, 2, 124, 'available', 2);
insert into ROOM values (default, 2, 125, 'available', 2);
insert into ROOM values (default, 3, 126, 'available', 2);
insert into ROOM values (default, 3, 127, 'available', 2);
insert into ROOM values (default, 3, 128, 'available', 2);
insert into ROOM values (default, 3, 129, 'available', 2);
insert into ROOM values (default, 3, 130, 'available', 2);
insert into ROOM values (default, 3, 131, 'available', 2);
insert into ROOM values (default, 3, 132, 'available', 2);
insert into ROOM values (default, 3, 133, 'available', 2);
insert into ROOM values (default, 3, 134, 'available', 2);
insert into ROOM values (default, 3, 135, 'available', 2);
insert into ROOM values (default, 4, 136, 'available', 2);
insert into ROOM values (default, 4, 137, 'available', 2);
insert into ROOM values (default, 4, 138, 'available', 2);
insert into ROOM values (default, 4, 139, 'available', 2);
insert into ROOM values (default, 4, 140, 'available', 2);
insert into ROOM values (default, 5, 141, 'available', 2);
insert into ROOM values (default, 5, 142, 'available', 2);

-- Brisbane hotel
insert into ROOM values (default, 1, 101, 'available', 3);
insert into ROOM values (default, 1, 102, 'available', 3);
insert into ROOM values (default, 1, 103, 'available', 3);
insert into ROOM values (default, 1, 104, 'available', 3);
insert into ROOM values (default, 1, 105, 'available', 3);
insert into ROOM values (default, 1, 106, 'available', 3);
insert into ROOM values (default, 1, 107, 'available', 3);
insert into ROOM values (default, 1, 108, 'available', 3);
insert into ROOM values (default, 1, 109, 'available', 3);
insert into ROOM values (default, 1, 110, 'available', 3);
insert into ROOM values (default, 1, 111, 'available', 3);
insert into ROOM values (default, 1, 112, 'available', 3);
insert into ROOM values (default, 1, 113, 'available', 3);
insert into ROOM values (default, 1, 114, 'available', 3);
insert into ROOM values (default, 1, 115, 'available', 3);
insert into ROOM values (default, 2, 116, 'available', 3);
insert into ROOM values (default, 2, 117, 'available', 3);
insert into ROOM values (default, 2, 118, 'available', 3);
insert into ROOM values (default, 2, 119, 'available', 3);
insert into ROOM values (default, 2, 120, 'available', 3);
insert into ROOM values (default, 2, 121, 'available', 3);
insert into ROOM values (default, 2, 122, 'available', 3);
insert into ROOM values (default, 2, 123, 'available', 3);
insert into ROOM values (default, 2, 124, 'available', 3);
insert into ROOM values (default, 2, 125, 'available', 3);
insert into ROOM values (default, 3, 126, 'available', 3);
insert into ROOM values (default, 3, 127, 'available', 3);
insert into ROOM values (default, 3, 128, 'available', 3);
insert into ROOM values (default, 3, 129, 'available', 3);
insert into ROOM values (default, 3, 130, 'available', 3);
insert into ROOM values (default, 3, 131, 'available', 3);
insert into ROOM values (default, 3, 132, 'available', 3);
insert into ROOM values (default, 3, 133, 'available', 3);
insert into ROOM values (default, 3, 134, 'available', 3);
insert into ROOM values (default, 3, 135, 'available', 3);
insert into ROOM values (default, 4, 136, 'available', 3);
insert into ROOM values (default, 4, 137, 'available', 3);
insert into ROOM values (default, 4, 138, 'available', 3);
insert into ROOM values (default, 4, 139, 'available', 3);
insert into ROOM values (default, 4, 140, 'available', 3);
insert into ROOM values (default, 5, 141, 'available', 3);
insert into ROOM values (default, 5, 142, 'available', 3);

-- Adelaide hotel
insert into ROOM values (default, 1, 101, 'available', 4);
insert into ROOM values (default, 1, 102, 'available', 4);
insert into ROOM values (default, 1, 103, 'available', 4);
insert into ROOM values (default, 1, 104, 'available', 4);
insert into ROOM values (default, 1, 105, 'available', 4);
insert into ROOM values (default, 1, 106, 'available', 4);
insert into ROOM values (default, 1, 107, 'available', 4);
insert into ROOM values (default, 1, 108, 'available', 4);
insert into ROOM values (default, 1, 109, 'available', 4);
insert into ROOM values (default, 1, 110, 'available', 4);
insert into ROOM values (default, 1, 111, 'available', 4);
insert into ROOM values (default, 1, 112, 'available', 4);
insert into ROOM values (default, 1, 113, 'available', 4);
insert into ROOM values (default, 1, 114, 'available', 4);
insert into ROOM values (default, 1, 115, 'available', 4);
insert into ROOM values (default, 2, 116, 'available', 4);
insert into ROOM values (default, 2, 117, 'available', 4);
insert into ROOM values (default, 2, 118, 'available', 4);
insert into ROOM values (default, 2, 119, 'available', 4);
insert into ROOM values (default, 2, 120, 'available', 4);
insert into ROOM values (default, 2, 121, 'available', 4);
insert into ROOM values (default, 2, 122, 'available', 4);
insert into ROOM values (default, 2, 123, 'available', 4);
insert into ROOM values (default, 2, 124, 'available', 4);
insert into ROOM values (default, 2, 125, 'available', 4);
insert into ROOM values (default, 3, 126, 'available', 4);
insert into ROOM values (default, 3, 127, 'available', 4);
insert into ROOM values (default, 3, 128, 'available', 4);
insert into ROOM values (default, 3, 129, 'available', 4);
insert into ROOM values (default, 3, 130, 'available', 4);
insert into ROOM values (default, 3, 131, 'available', 4);
insert into ROOM values (default, 3, 132, 'available', 4);
insert into ROOM values (default, 3, 133, 'available', 4);
insert into ROOM values (default, 3, 134, 'available', 4);
insert into ROOM values (default, 3, 135, 'available', 4);
insert into ROOM values (default, 4, 136, 'available', 4);
insert into ROOM values (default, 4, 137, 'available', 4);
insert into ROOM values (default, 4, 138, 'available', 4);
insert into ROOM values (default, 4, 139, 'available', 4);
insert into ROOM values (default, 4, 140, 'available', 4);
insert into ROOM values (default, 5, 141, 'available', 4);
insert into ROOM values (default, 5, 142, 'available', 4);

-- Hobart hotel
insert into ROOM values (default, 1, 101, 'available', 5);
insert into ROOM values (default, 1, 102, 'available', 5);
insert into ROOM values (default, 1, 103, 'available', 5);
insert into ROOM values (default, 1, 104, 'available', 5);
insert into ROOM values (default, 1, 105, 'available', 5);
insert into ROOM values (default, 1, 106, 'available', 5);
insert into ROOM values (default, 1, 107, 'available', 5);
insert into ROOM values (default, 1, 108, 'available', 5);
insert into ROOM values (default, 1, 109, 'available', 5);
insert into ROOM values (default, 1, 110, 'available', 5);
insert into ROOM values (default, 1, 111, 'available', 5);
insert into ROOM values (default, 1, 112, 'available', 5);
insert into ROOM values (default, 1, 113, 'available', 5);
insert into ROOM values (default, 1, 114, 'available', 5);
insert into ROOM values (default, 1, 115, 'available', 5);
insert into ROOM values (default, 2, 116, 'available', 5);
insert into ROOM values (default, 2, 117, 'available', 5);
insert into ROOM values (default, 2, 118, 'available', 5);
insert into ROOM values (default, 2, 119, 'available', 5);
insert into ROOM values (default, 2, 120, 'available', 5);
insert into ROOM values (default, 2, 121, 'available', 5);
insert into ROOM values (default, 2, 122, 'available', 5);
insert into ROOM values (default, 2, 123, 'available', 5);
insert into ROOM values (default, 2, 124, 'available', 5);
insert into ROOM values (default, 2, 125, 'available', 5);
insert into ROOM values (default, 3, 126, 'available', 5);
insert into ROOM values (default, 3, 127, 'available', 5);
insert into ROOM values (default, 3, 128, 'available', 5);
insert into ROOM values (default, 3, 129, 'available', 5);
insert into ROOM values (default, 3, 130, 'available', 5);
insert into ROOM values (default, 3, 131, 'available', 5);
insert into ROOM values (default, 3, 132, 'available', 5);
insert into ROOM values (default, 3, 133, 'available', 5);
insert into ROOM values (default, 3, 134, 'available', 5);
insert into ROOM values (default, 3, 135, 'available', 5);
insert into ROOM values (default, 4, 136, 'available', 5);
insert into ROOM values (default, 4, 137, 'available', 5);
insert into ROOM values (default, 4, 138, 'available', 5);
insert into ROOM values (default, 4, 139, 'available', 5);
insert into ROOM values (default, 4, 140, 'available', 5);
insert into ROOM values (default, 5, 141, 'available', 5);
insert into ROOM values (default, 5, 142, 'available', 5);

insert into CUSTOMER values (default, 'Andrew', 'Anderson');
insert into CUSTOMER values (default, 'Bill', 'Bite');
insert into CUSTOMER values (default, 'Claire', 'Eclair');
insert into CUSTOMER values (default, 'Daniel', 'Danish');
insert into CUSTOMER values (default, 'Ethan', 'Ether');
insert into CUSTOMER values (default, 'Frank', 'Fryer');
insert into CUSTOMER values (default, 'Gary', 'Grey');
insert into CUSTOMER values (default, 'Harold', 'Haroldson');

insert into STAFF values (default, 'Sandy', 'Sandy', 'password', 'manager');
insert into STAFF values (default, 'Jason', 'Jason', 'password', 'manager');
insert into STAFF values (default, 'Kate', 'Kate', 'password', 'owner');

insert into DISCOUNT values (default, 2, '2014-05-01', '2014-05-31', 90, 1);
